name: blockpuzzler
description: A puzzle game for android
publish_to: "none"
version: 0.1.1

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    flame: ^1.8.1
    flutter:
        sdk: flutter
    package_info_plus: ^4.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/Blue.png
        - assets/images/Red.png
        - assets/images/Green.png
        - assets/images/Yellow.png
    fonts:
        - family: Lumanosimo
          fonts:
            - asset: assets/fonts/Lumanosimo-Regular.ttf 
              style: normal
