name: blockpuzzler
description: A puzzle game for android
publish_to: "none"
version: 0.1.1

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    flame: ^1.8.1
    flutter:
        sdk: flutter
    package_info_plus: ^4.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/Tiles/Blue.png
        - assets/images/Tiles/Red.png
        - assets/images/Tiles/Green.png
        - assets/images/Tiles/Yellow.png
        - assets/images/Paths/lt.png
        - assets/images/Paths/lb.png
        - assets/images/Paths/rt.png
        - assets/images/Paths/rb.png
        - assets/images/Paths/end.png
        - assets/images/Paths/err.png
        - assets/images/Paths/horizontal.png
        - assets/images/Paths/vertical.png
    fonts:
        - family: Lumanosimo
          fonts:
              - asset: assets/fonts/Lumanosimo-Regular.ttf
                style: normal
